(function(){
"use strict";
var C=window.JUST_US_CONFIG||{};
var app=document.getElementById("app"),toast=document.getElementById("toast"),topStatus=document.getElementById("topStatus");
var state={room:null,deviceId:null,name:"",page:"home",messages:[],poll:null,avatar:"",draftAvatar:null,cropScale:1,cropX:0,cropY:0,drag:false,dragX:0,dragY:0};
function uid(){return "d-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8)}
state.deviceId=localStorage.getItem("justus_device_id")||uid();localStorage.setItem("justus_device_id",state.deviceId);
state.name=localStorage.getItem("justus_name")||"You";state.avatar=localStorage.getItem("justus_avatar")||"";
function esc(s){return String(s==null?"":s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}
function showToast(s){toast.textContent=s;toast.className="toast show";setTimeout(function(){toast.className="toast"},2400)}
function cfgOk(){return C.SUPABASE_URL&&C.SUPABASE_URL.indexOf("https://")===0&&C.SUPABASE_ANON_KEY&&C.SUPABASE_ANON_KEY.indexOf("YOUR-")!==0}
function api(path,method,body,prefer){return new Promise(function(resolve,reject){if(!cfgOk()){reject(new Error("Add your Supabase URL and publishable/anon key in config.js"));return}var x=new XMLHttpRequest();x.open(method||"GET",C.SUPABASE_URL+"/rest/v1/"+path,true);x.setRequestHeader("apikey",C.SUPABASE_ANON_KEY);x.setRequestHeader("Authorization","Bearer "+C.SUPABASE_ANON_KEY);x.setRequestHeader("Content-Type","application/json");if(prefer)x.setRequestHeader("Prefer",prefer);x.onreadystatechange=function(){if(x.readyState!==4)return;var d=null;try{d=x.responseText?JSON.parse(x.responseText):null}catch(e){}if(x.status>=200&&x.status<300)resolve(d);else reject(new Error((d&&d.message)||x.responseText||("HTTP "+x.status)))};x.onerror=function(){reject(new Error("Network error"))};x.send(body?JSON.stringify(body):null)})}
function rpc(fn,body){return new Promise(function(resolve,reject){if(!cfgOk()){reject(new Error("Add your Supabase URL and publishable/anon key in config.js"));return}var x=new XMLHttpRequest();x.open("POST",C.SUPABASE_URL+"/rest/v1/rpc/"+fn,true);x.setRequestHeader("apikey",C.SUPABASE_ANON_KEY);x.setRequestHeader("Authorization","Bearer "+C.SUPABASE_ANON_KEY);x.setRequestHeader("Content-Type","application/json");x.onreadystatechange=function(){if(x.readyState!==4)return;var d=null;try{d=x.responseText?JSON.parse(x.responseText):null}catch(e){}if(x.status>=200&&x.status<300)resolve(d);else reject(new Error((d&&d.message)||x.responseText||("HTTP "+x.status)))};x.onerror=function(){reject(new Error("Network error"))};x.send(JSON.stringify(body||{}))})}
function cleanCode(v){return String(v||"").trim().replace(/\s+/g,"").toUpperCase()}
function avatarHtml(src,name,cls){return src?'<img class="avatar '+(cls||"")+ '" src="'+esc(src)+'" alt="">':'<div class="avatar avatar-fallback '+(cls||"")+'">'+esc((name||"Y").charAt(0).toUpperCase())+'</div>'}
function home(){stopPoll();state.page="home";setNav("home");app.innerHTML='<section class="home-hero"><div><div class="eyebrow">PRIVATE • JUST TWO</div><h1>Your little<br><em>private world.</em></h1><p>One room. One person. No feed, no noise — just your space.</p></div>'+avatarHtml(state.avatar,state.name,"hero-avatar")+'</section><section class="quick-grid"><button class="quick-card chat-card" id="homeChat"><span class="quick-icon">♡</span><b>Chat</b><small>Talk privately</small></button><button class="quick-card" id="homeMoments"><span class="quick-icon">✦</span><b>Moments</b><small>Little memories</small></button><button class="quick-card" id="homePlay"><span class="quick-icon">◉</span><b>Play</b><small>Games for two</small></button><button class="quick-card" id="homeSettings"><span class="quick-icon">⚙</span><b>Your profile</b><small>Photo & settings</small></button></section><section class="room-panel panel"><div class="section-title"><div><span class="eyebrow">PRIVATE ROOM</span><h2>Connect your two phones</h2></div><span class="lock">⌁</span></div><div class="room-actions"><button class="primary" id="createBtn">Create private room</button><div class="join-line"><input id="joinCode" class="code-input" maxlength="12" inputmode="text" autocomplete="off" placeholder="ROOM CODE"><button class="secondary" id="joinBtn">Join</button></div></div><p class="tiny-note">Enter the exact same code on the other phone.</p></section>';
document.getElementById("createBtn").onclick=createRoom;document.getElementById("joinBtn").onclick=joinRoom;document.getElementById("homeChat").onclick=function(){if(state.room)roomPage();else showToast("Create or join a room first")};document.getElementById("homeMoments").onclick=function(){simplePage("moments")};document.getElementById("homePlay").onclick=function(){simplePage("play")};document.getElementById("homeSettings").onclick=settingsPage}
function createRoom(){var b=document.getElementById("createBtn");b.disabled=true;b.textContent="Creating…";rpc("create_private_room",{p_device_id:state.deviceId,p_display_name:state.name}).then(function(r){state.room=r[0]||r;localStorage.setItem("justus_room_code",state.room.code);showToast("Room created: "+state.room.code);roomPage()}).catch(function(e){showToast(e.message)}).then(function(){b.disabled=false;b.textContent="Create private room"})}
function joinRoom(){var code=cleanCode(document.getElementById("joinCode").value);if(!code){showToast("Enter the room code");return}var b=document.getElementById("joinBtn");b.disabled=true;b.textContent="Joining…";rpc("join_private_room",{p_code:code,p_device_id:state.deviceId,p_display_name:state.name}).then(function(r){state.room=r[0]||r;localStorage.setItem("justus_room_code",state.room.code);showToast("Connected to "+state.room.code);roomPage()}).catch(function(e){showToast(e.message)}).then(function(){b.disabled=false;b.textContent="Join"})}
function roomPage(){state.page="chat";setNav("chat");topStatus.textContent="private chat";app.innerHTML='<section class="chat-screen"><header class="chat-head"><button class="back-btn" id="chatBack">‹</button><div class="chat-person">'+avatarHtml(state.avatar,"You","chat-avatar")+'<div><b>Just Us</b><span id="partnerStatus">Private space • room '+esc(state.room.code)+'</span></div></div><div class="chat-head-actions"><button class="icon-btn" id="callBtn">⌕</button><button class="icon-btn" id="chatMore">⋮</button></div></header><div class="chat-wallpaper" id="chatbox"><div class="empty-chat"><div>♡</div><b>Your private conversation</b><span>Messages stay inside room '+esc(state.room.code)+'.</span></div></div><form class="message-bar" id="messageForm"><button type="button" class="plus-btn" id="plusBtn">＋</button><input id="msgInput" maxlength="1000" autocomplete="off" placeholder="Message"><button type="submit" class="send-btn">➤</button></form></section>';
document.getElementById("chatBack").onclick=home;document.getElementById("messageForm").onsubmit=function(e){e.preventDefault();sendMessage()};document.getElementById("plusBtn").onclick=function(){showToast("Attachments can be added here")};document.getElementById("callBtn").onclick=function(){showToast("Calling is not enabled in this lightweight chat yet")};document.getElementById("chatMore").onclick=function(){settingsPage()};loadMessages();startPoll()}
function loadMessages(){api("messages?room_id=eq."+encodeURIComponent(state.room.id)+"&select=id,device_id,display_name,body,created_at&order=created_at.asc&limit=100","GET").then(function(rows){state.messages=rows||[];renderMessages()}).catch(function(e){showToast(e.message)})}
function renderMessages(){var box=document.getElementById("chatbox");if(!box)return;if(!state.messages.length){box.innerHTML='<div class="empty-chat"><div>♡</div><b>Your private conversation</b><span>Say something small.</span></div>';return}box.innerHTML=state.messages.map(function(m){return '<div class="msg-row '+(m.device_id===state.deviceId?"mine":"theirs")+'">'+(m.device_id===state.deviceId?"":avatarHtml("",m.display_name,"mini-avatar"))+'<div class="msg '+(m.device_id===state.deviceId?"mine":"theirs")+'"><div>'+esc(m.body)+'</div><small>'+esc(m.display_name||"You")+' · '+new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})+'</small></div></div>'}).join("");box.scrollTop=box.scrollHeight}
function sendMessage(){var input=document.getElementById("msgInput"),body=(input.value||"").trim();if(!body||!state.room)return;input.disabled=true;api("messages","POST",{room_id:state.room.id,device_id:state.deviceId,display_name:state.name,body:body},"return=minimal").then(function(){input.value="";loadMessages()}).catch(function(e){showToast(e.message)}).then(function(){input.disabled=false;input.focus()})}
function startPoll(){stopPoll();state.poll=setInterval(function(){if(state.room)loadMessages()},2500)}function stopPoll(){if(state.poll){clearInterval(state.poll);state.poll=null}}
function leaveRoom(){stopPoll();state.room=null;topStatus.textContent="private space";home()}
function settingsPage(){stopPoll();setNav("");state.page="settings";app.innerHTML='<section class="settings-page"><div class="settings-title"><button class="back-btn" id="settingsBack">‹</button><div><div class="eyebrow">YOUR SPACE</div><h1>Profile & settings</h1></div></div><section class="profile-card"><label class="profile-photo" for="avatarInput">'+avatarHtml(state.avatar,state.name,"profile-avatar")+'<span>＋</span></label><input id="avatarInput" type="file" accept="image/*" class="sr-only"><div><h2>'+esc(state.name)+'</h2><p>Your profile photo is stored on this device. Crop it before using it.</p></div></section><section class="settings-list"><label><span><b>Your name</b><small>Name shown in chat</small></span><input id="nameInput" value="'+esc(state.name)+'" maxlength="30"></label><label class="setting-toggle"><span><b>Haptics in chat</b><small>Off by default for a quieter chat</small></span><input id="hapticToggle" type="checkbox"><i></i></label></section><section class="settings-info"><b>Older-phone friendly</b><p>Chat avoids heavy effects and uses lightweight polling, so it stays usable on slower browsers.</p></section></section>';
document.getElementById("settingsBack").onclick=function(){state.room?roomPage():home()};document.getElementById("nameInput").onchange=function(){state.name=this.value.trim()||"You";localStorage.setItem("justus_name",state.name);showToast("Name saved")};document.getElementById("avatarInput").onchange=handleAvatarFile;var h=localStorage.getItem("justus_haptics")==="1";document.getElementById("hapticToggle").checked=h;document.getElementById("hapticToggle").onchange=function(){localStorage.setItem("justus_haptics",this.checked?"1":"0");showToast(this.checked?"Haptics on":"Haptics off")}}
function simplePage(n){stopPoll();setNav(n);app.innerHTML='<section class="simple-page"><button class="back-btn" id="simpleBack">‹</button><div class="eyebrow">JUST US</div><h1>'+esc(n.charAt(0).toUpperCase()+n.slice(1))+'.</h1><p>This space is kept intentionally simple so older phones do not have to load heavy features.</p></section>';document.getElementById("simpleBack").onclick=home}
function handleAvatarFile(e){var file=e.target.files&&e.target.files[0];if(!file)return;if(file.size>8*1024*1024){showToast("Choose a photo under 8 MB");return}var reader=new FileReader();reader.onload=function(){state.draftAvatar=reader.result;openCrop(reader.result)};reader.readAsDataURL(file)}
function openCrop(src){var modal=document.getElementById("cropModal"),img=document.getElementById("cropImage");modal.className="modal";modal.setAttribute("aria-hidden","false");img.src=src;state.cropScale=1;state.cropX=0;state.cropY=0;img.style.transform="translate(0px,0px) scale(1)"}
function closeCrop(){var modal=document.getElementById("cropModal");modal.className="modal hidden";modal.setAttribute("aria-hidden","true")}
function saveCrop(){var img=document.getElementById("cropImage"),canvas=document.createElement("canvas"),size=600,ctx=canvas.getContext("2d"),naturalW=img.naturalWidth,naturalH=img.naturalHeight,cover=Math.max(size/naturalW,size/naturalH),scale=cover*state.cropScale,w=naturalW*scale,h=naturalH*scale;canvas.width=size;canvas.height=size;ctx.fillStyle="#111";ctx.fillRect(0,0,size,size);ctx.drawImage(img,(size-w)/2+state.cropX,(size-h)/2+state.cropY,w,h);try{state.avatar=canvas.toDataURL("image/jpeg",.82);localStorage.setItem("justus_avatar",state.avatar);closeCrop();showToast("Profile photo saved");settingsPage()}catch(e){showToast("Could not save this photo")}}
function bindCrop(){var stage=document.querySelector(".crop-stage"),img=document.getElementById("cropImage");stage.onwheel=function(e){e.preventDefault();state.cropScale=Math.max(.7,Math.min(3,state.cropScale+(e.deltaY<0?.08:-.08)));img.style.transform="translate("+state.cropX+"px,"+state.cropY+"px) scale("+state.cropScale+")"};stage.onpointerdown=function(e){state.drag=true;state.dragX=e.clientX;state.dragY=e.clientY;stage.setPointerCapture&&stage.setPointerCapture(e.pointerId)};stage.onpointermove=function(e){if(!state.drag)return;state.cropX+=e.clientX-state.dragX;state.cropY+=e.clientY-state.dragY;state.dragX=e.clientX;state.dragY=e.clientY;img.style.transform="translate("+state.cropX+"px,"+state.cropY+"px) scale("+state.cropScale+")"};stage.onpointerup=function(){state.drag=false};stage.onpointercancel=function(){state.drag=false}}
function setNav(n){document.querySelectorAll(".nav-item").forEach(function(b){b.className="nav-item "+(b.getAttribute("data-nav")===n?"active":"")})}
document.querySelectorAll("[data-nav]").forEach(function(b){b.onclick=function(){var n=b.getAttribute("data-nav");if(n==="home")home();else if(n==="chat"){if(state.room)roomPage();else{home();showToast("Create or join a room first")}}else simplePage(n)}});
document.getElementById("settingsBtn").onclick=settingsPage;document.querySelector("[data-action=home]").onclick=function(e){e.preventDefault();home()};document.getElementById("closeCrop").onclick=closeCrop;document.getElementById("cancelCrop").onclick=closeCrop;document.getElementById("saveCrop").onclick=saveCrop;bindCrop();home();
})();
