import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient,RealtimeChannel,SupabaseClient} from '@supabase/supabase-js';
import {ArrowLeft,ArrowRight,Bell,Camera,Check,CheckCheck,ChevronDown,ChevronRight,Copy,Download,File as FileIcon,Gamepad2,Heart,Home,Image as ImageIcon,LockKeyhole,Menu,MessageCircle,Mic,MicOff,MoreVertical,Paperclip,Phone,Play,Plus,RefreshCw,ScreenShare,Send,Settings,ShieldCheck,Smile,Sparkles,Square,Trash2,Upload,UserRound,Users,Video,Volume2,VolumeX,Wifi,WifiOff,X,Zap} from 'lucide-react';
import './styles.css';

type Tab='home'|'chat'|'moments'|'play';
type Message={id:string;room_id?:string;sender_id:string;text:string;kind:'text'|'image'|'file';file_url?:string;file_name?:string;mime_type?:string;created_at:string;status?:'sent'|'delivered'|'read';reply_to?:string};
type Moment={id:string;sender_id:string;caption:string;image_url:string;created_at:string};
type Profile={name:string;code:string;avatar:string};
type Toast={id:number;text:string;kind:'info'|'success'|'error'};

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'';
const SUPABASE_ANON_KEY=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const sb:SupabaseClient|null=SUPABASE_URL&&SUPABASE_ANON_KEY?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const clock=(d=new Date())=>new Intl.DateTimeFormat([], {hour:'2-digit',minute:'2-digit'}).format(d);
const ago=(iso:string)=>{const n=Date.now()-new Date(iso).getTime();const m=Math.floor(n/60000);if(m<1)return'online';if(m<60)return`${m} min ago`;const h=Math.floor(m/60);if(h<24)return`${h} hr ago`;return`${Math.floor(h/24)} d ago`};
function haptic(type:'light'|'medium'|'success'|'error'='light'){try{navigator.vibrate?.(type==='success'?[8,30,8]:type==='error'?[18,40,18]:type==='medium'?16:8)}catch{}}
function App(){
 const [tab,setTab]=useState<Tab>((new URLSearchParams(location.search).get('tab') as Tab)||'home');
 const [step,setStep]=useState<'welcome'|'privacy'|'profile'|'room'|'app'>(()=>localStorage.getItem('justus.profile')?'room':'welcome');
 const [profile,setProfile]=useState<Profile>(()=>JSON.parse(localStorage.getItem('justus.profile')||'{"name":"","code":"","avatar":""}'));
 const [roomCode,setRoomCode]=useState(()=>localStorage.getItem('justus.room')||'');
 const [roomId,setRoomId]=useState('');
 const [userId,setUserId]=useState(()=>localStorage.getItem('justus.uid')||uid());
 const [partner,setPartner]=useState<{id:string;name:string;avatar:string;lastSeen:number;online:boolean}|null>(null);
 const [messages,setMessages]=useState<Message[]>([]);
 const [moments,setMoments]=useState<Moment[]>([]);
 const [toasts,setToasts]=useState<Toast[]>([]);
 const [backendReady,setBackendReady]=useState(!!sb);
 const [channel,setChannel]=useState<RealtimeChannel|null>(null);
 const [installPrompt,setInstallPrompt]=useState<any>(null);
 const [call,setCall]=useState<CallState|null>(null);const [pendingSignal,setPendingSignal]=useState<any>(null);
 useEffect(()=>{localStorage.setItem('justus.uid',userId)},[userId]);
 useEffect(()=>{const f=(e:any)=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',f);return()=>window.removeEventListener('beforeinstallprompt',f)},[]);
 const toast=useCallback((text:string,kind:Toast['kind']='info')=>{const id=Date.now();setToasts(v=>[...v,{id,text,kind}]);setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),2800)},[]);
 const saveProfile=(p:Profile)=>{setProfile(p);localStorage.setItem('justus.profile',JSON.stringify(p))};
 const createRoom=()=>{const c=String(Math.floor(10000+Math.random()*90000));setRoomCode(c);localStorage.setItem('justus.room',c);setStep('app');toast('Private room created','success');haptic('success')};
 const joinRoom=async(c:string)=>{if(!/^\d{5}$/.test(c))return toast('Enter the 5-digit room code','error');setRoomCode(c);localStorage.setItem('justus.room',c);setStep('app');toast('Joining room…','info');haptic('medium')};
 useEffect(()=>{if(!sb||step!=='app'||!roomCode)return;let alive=true;(async()=>{const {data}=await sb.auth.getSession();if(!data.session){const r=await sb.auth.signInAnonymously();if(r.error){setBackendReady(false);toast('Backend authentication is not configured','error');return}}if(!alive)return;const {data:room}=await sb.from('rooms').select('id').eq('code',roomCode).maybeSingle();if(room)setRoomId(room.id);else{const {data:nr}=await sb.from('rooms').insert({code:roomCode}).select('id').single();if(nr)setRoomId(nr.id)}setBackendReady(true)})();return()=>{alive=false}},[step,roomCode]);
 useEffect(()=>{
  if(!sb||!roomId||!profile.name)return;
  let ch:RealtimeChannel|undefined; let beat:number|undefined; let alive=true;
  (async()=>{
   const {data:{user}}=await sb!.auth.getUser(); if(!user||!alive)return; setUserId(user.id);
   await sb!.from('room_members').upsert({room_id:roomId,user_id:user.id,display_name:profile.name,avatar_url:profile.avatar||null,last_seen:new Date().toISOString()},{onConflict:'room_id,user_id'});
   const {data:members}=await sb!.from('room_members').select('*').eq('room_id',roomId).neq('user_id',user.id).limit(1);
   if(members?.[0])setPartner({id:members[0].user_id,name:members[0].display_name,avatar:members[0].avatar_url||'',lastSeen:new Date(members[0].last_seen).getTime(),online:false});
   const {data:ms}=await sb!.from('messages').select('*').eq('room_id',roomId).order('created_at',{ascending:true}); if(ms)setMessages(ms as Message[]);
   const {data:mm}=await sb!.from('moments').select('*').eq('room_id',roomId).order('created_at',{ascending:false}); if(mm)setMoments(mm as Moment[]);
   ch=sb!.channel(`room:${roomId}`,{config:{presence:{key:user.id}}})
    .on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`room_id=eq.${roomId}`},p=>{const m=p.new as Message;setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m])})
    .on('postgres_changes',{event:'INSERT',schema:'public',table:'moments',filter:`room_id=eq.${roomId}`},p=>setMoments(v=>v.some(x=>x.id===(p.new as Moment).id)?v:[p.new as Moment,...v]))
    .on('presence',{event:'sync'},()=>{const state=ch!.presenceState();const others=Object.entries(state).filter(([k])=>k!==user.id);if(others[0]){const x:any=others[0][1][0];setPartner(p=>({id:others[0][0],name:x.name||p?.name||'Your person',avatar:x.avatar||p?.avatar||'',lastSeen:Date.now(),online:true}))}else setPartner(p=>p?{...p,online:false,lastSeen:Date.now()}:null)})
    .on('broadcast',{event:'call-signal'},({payload}:any)=>{window.dispatchEvent(new CustomEvent('justus-call',{detail:payload}));if(payload?.from!==user.id&&payload?.type==='offer'){setPendingSignal(payload);setCall({video:!!payload.video,initiator:false})}});
   await ch.subscribe(async status=>{if(status==='SUBSCRIBED')await ch!.track({name:profile.name,avatar:profile.avatar||'',online:true})});
   setChannel(ch); beat=window.setInterval(()=>{sb!.from('room_members').update({last_seen:new Date().toISOString()}).eq('room_id',roomId).eq('user_id',user.id)},30000);
  })();
  return()=>{alive=false;if(beat)clearInterval(beat);if(ch)sb!.removeChannel(ch);setChannel(null)};
 },[roomId,profile.name,profile.avatar]);

 const sendMessage=async(m:Omit<Message,'id'|'sender_id'|'created_at'>)=>{const base={...m,id:uid(),sender_id:userId,created_at:new Date().toISOString(),status:'sent' as const};if(sb&&roomId){const {error}=await sb.from('messages').insert({...base,room_id:roomId});if(error){toast('Message could not be sent','error');return}}else setMessages(v=>[...v,base]);haptic('light')};
 const sendMoment=async(caption:string,file:File)=>{const localUrl=URL.createObjectURL(file);if(sb&&roomId){const path=`${roomId}/${uid()}-${file.name.replace(/[^a-z0-9._-]/gi,'_')}`;const up=await sb.storage.from('moments').upload(path,file,{upsert:false});if(up.error){toast('Storage bucket is not configured; using local preview','error');setMoments(v=>[{id:uid(),sender_id:userId,caption,image_url:localUrl,created_at:new Date().toISOString()},...v]);return}const {data}=sb.storage.from('moments').getPublicUrl(path);const {data:row,error}=await sb.from('moments').insert({room_id:roomId,sender_id:userId,caption,image_url:data.publicUrl}).select('*').single();if(error){toast('Moment record failed','error');return}setMoments(v=>[row as Moment,...v]);toast('Moment shared','success')}else{setMoments(v=>[{id:uid(),sender_id:userId,caption,image_url:localUrl,created_at:new Date().toISOString()},...v]);toast('Moment added locally','success')}haptic('success')};
 const leave=()=>{localStorage.removeItem('justus.room');setRoomCode('');setRoomId('');setStep('room');toast('Left room','info')};
 if(step!=='app')return <><Onboarding step={step} setStep={setStep} profile={profile} saveProfile={saveProfile} roomCode={roomCode} setRoomCode={setRoomCode} createRoom={createRoom} joinRoom={joinRoom} toast={toast}/><Toasts items={toasts}/></>;
 return <div className="app"><Header profile={profile} partner={partner} onCall={(video)=>setCall({video,initiator:true})} toast={toast} online={backendReady}/><main>{tab==='home'&&<HomeView profile={profile} partner={partner} roomCode={roomCode} backendReady={backendReady} setTab={setTab} installPrompt={installPrompt} toast={toast}/>} {tab==='chat'&&<ChatView messages={messages} sendMessage={sendMessage} partner={partner} profile={profile} toast={toast}/>} {tab==='moments'&&<MomentsView moments={moments} userId={userId} sendMoment={sendMoment} toast={toast}/>} {tab==='play'&&<GamesView toast={toast}/>}</main><Bottom tab={tab} setTab={setTab}/>{call&&<CallOverlay call={call} profile={profile} partner={partner} channel={channel} userId={userId} pendingSignal={pendingSignal} close={()=>{setCall(null);setPendingSignal(null)}} toast={toast}/>}<Toasts items={toasts}/><button className="floating-help" onClick={()=>toast('Long-press a message for actions • calls require the live backend','info')} aria-label="Help">?</button></div>;
}
function Onboarding({step,setStep,profile,saveProfile,roomCode,setRoomCode,createRoom,joinRoom,toast}:{step:any;setStep:any;profile:Profile;saveProfile:(p:Profile)=>void;roomCode:string;setRoomCode:(s:string)=>void;createRoom:()=>void;joinRoom:(s:string)=>void;toast:any}){
 const [avatar,setAvatar]=useState(profile.avatar);const [name,setName]=useState(profile.name);const [code,setCode]=useState(profile.code||String(Math.floor(10000+Math.random()*90000)));const [zoom,setZoom]=useState(1);const [pos,setPos]=useState({x:0,y:0});
 const choose=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setAvatar(String(r.result));r.readAsDataURL(f)};
 if(step==='welcome')return <div className="entry"><div className="entry-orb"/><section className="welcome-card"><div className="brand-mark"><Sparkles size={19}/></div><h1>Just Us <span>♡</span></h1><p>A tiny private world for two.<br/>Take a breath. This space is yours.</p><button className="primary" onClick={()=>{setStep('privacy');haptic('medium')}}>Enter our little world <Sparkles size={16}/></button><small>First-time setup · works as a mobile web app</small></section></div>;
 if(step==='privacy')return <div className="entry"><section className="article-card"><div className="eyebrow">A NOTE FROM JUST US</div><h2>Private by design</h2><p>Messages, moments, and calls should belong to the two people using them. This interface is prepared for a client-side encrypted architecture.</p><div className="privacy-note"><LockKeyhole size={18}/><div><b>Important</b><span>A visual interface does not create end-to-end encryption. Production E2EE must use audited cryptography, authenticated key exchange and secure key storage.</span></div></div><button className="primary" onClick={()=>setStep('profile')}>Continue <ArrowRight size={17}/></button></section></div>;
 if(step==='profile')return <div className="entry"><section className="profile-card"><div className="eyebrow">YOUR PROFILE</div><h2>Just you two</h2><p>Choose the photo and name your person will see.</p><label className="avatar-upload"><input type="file" accept="image/*" onChange={choose}/>{avatar?<img src={avatar} style={{transform:`scale(${zoom}) translate(${pos.x}px,${pos.y}px)`}}/>:<UserRound size={42}/>}<span><Camera size={15}/> Add profile photo</span></label>{avatar&&<div className="crop-tools"><label>Zoom <input type="range" min="1" max="2" step="0.05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><label>Horizontal <input type="range" min="-35" max="35" value={pos.x} onChange={e=>setPos({...pos,x:Number(e.target.value)})}/></label><label>Vertical <input type="range" min="-35" max="35" value={pos.y} onChange={e=>setPos({...pos,y:Number(e.target.value)})}/></label></div>}<label className="field"><span>Name</span><input value={name} maxLength={40} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><div className="code-row"><div><span>Private code</span><b>{code}</b></div><button className="icon-btn" onClick={()=>setCode(String(Math.floor(10000+Math.random()*90000)))}><RefreshCw size={17}/></button><button className="icon-btn" onClick={()=>{navigator.clipboard?.writeText(code);toast('Code copied','success')}}><Copy size={17}/></button></div><button className="primary" onClick={()=>{if(!name.trim())return toast('Enter your name','error');saveProfile({name,code,avatar});setStep('room');haptic('success')}}>Continue <ArrowRight size={17}/></button></section></div>;
 return <div className="entry"><section className="room-card"><Avatar src={avatar} name={name||'You'} /><div className="eyebrow">PRIVATE ROOM</div><h2>Just you two</h2><p>Create a room or enter the 5-digit code shared by your person.</p><button className="primary" onClick={createRoom}>Create private room <Sparkles size={16}/></button><div className="or">OR</div><input className="room-input" inputMode="numeric" maxLength={5} value={roomCode} onChange={e=>setRoomCode(e.target.value.replace(/\D/g,'').slice(0,5))} placeholder="ROOM CODE"/><button className="secondary" onClick={()=>joinRoom(roomCode)}>Join with code <ArrowRight size={16}/></button><p className="tiny">Use the same code on the other phone. With the live backend configured, both devices share one room timeline and presence.</p></section></div>
}
function Header({profile,partner,onCall,toast,online}:{profile:Profile;partner:any;onCall:(v:boolean)=>void;toast:any;online:boolean}){return <header><div className="header-title"><span className="wordmark">Just Us ♡</span><span className={`space-state ${online?'live':''}`}><i/> {online?'live space':'demo space'}</span></div><div className="partner-strip"><Avatar src={partner?.avatar} name={partner?.name||'Your person'} small/><div><b>{partner?.name||'Your person'}</b><span className={partner?.online?'online':''}>{partner?.online?'online':partner?ago(new Date(partner.lastSeen).toISOString()):'waiting to join'}</span></div><div className="header-actions"><button className="icon-btn" onClick={()=>onCall(false)} aria-label="Voice call"><Phone size={19}/></button><button className="icon-btn" onClick={()=>onCall(true)} aria-label="Video call"><Video size={20}/></button><button className="icon-btn" onClick={()=>toast('Room settings are in Profile','info')}><MoreVertical size={20}/></button></div></div></header>}
function Bottom({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){return <nav className="bottom"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/><span>Home</span></button><button className={tab==='chat'?'active':''} onClick={()=>setTab('chat')}><Heart/><span>Chat</span></button><button className={tab==='moments'?'active':''} onClick={()=>setTab('moments')}><Sparkles/><span>Moments</span></button><button className={tab==='play'?'active':''} onClick={()=>setTab('play')}><Gamepad2/><span>Play</span></button></nav>}
function HomeView({profile,partner,roomCode,backendReady,setTab,installPrompt,toast}:{profile:Profile;partner:any;roomCode:string;backendReady:boolean;setTab:(t:Tab)=>void;installPrompt:any;toast:any}){return <section className="home page"><div className="home-hero"><span className="eyebrow">YOUR LITTLE WORLD</span><h2>Just you two</h2><p>Room <b>{roomCode}</b> · {partner?.online?'together now':'waiting for your person'}</p></div><div className="home-grid"><ActionCard icon="💬" title="Chat" text="Private conversation, replies and attachments." onClick={()=>setTab('chat')}/><ActionCard icon="📹" title="Voice & video" text="WebRTC calling with mute, camera, share and decline." onClick={()=>toast('Tap the phone/video icon in the header to start a call','info')}/><ActionCard icon="📸" title="Moments" text="Send a photo with your own 15–20 word message." onClick={()=>setTab('moments')}/><ActionCard icon="🎲" title="Games" text="Play Ludo or Carrom together." onClick={()=>setTab('play')}/><ActionCard icon="🔐" title="Privacy" text="Real E2EE requires the configured production crypto layer." onClick={()=>toast('See Profile → Privacy & setup','info')}/><ActionCard icon="📱" title="Add to home" text={installPrompt?'Install Just Us like an app.':'Use your browser menu → Add to Home screen.'} onClick={async()=>{if(installPrompt){await installPrompt.prompt();setTimeout(()=>location.reload(),500)}else toast('Chrome: ⋮ → Add to Home screen → Add','info')}}/></div></section>}
function ActionCard({icon,title,text,onClick}:{icon:string;title:string;text:string;onClick:()=>void}){return <button className="action-card" onClick={()=>{haptic('light');onClick()}}><span className="emoji-icon">{icon}</span><div><h3>{title}</h3><p>{text}</p></div><ChevronRight/></button>}
function Avatar({src,name,small=false}:{src?:string;name:string;small?:boolean}){return <div className={`avatar ${small?'small':''}`}>{src?<img src={src} alt=""/>:<span>{name?.trim()?.[0]?.toUpperCase()||'♡'}</span>}</div>}
function ChatView({messages,sendMessage,partner,profile,toast}:{messages:Message[];sendMessage:(m:any)=>Promise<void>;partner:any;profile:Profile;toast:any}){
 const [text,setText]=useState('');
 const [reply,setReply]=useState<Message|null>(null);
 const [emoji,setEmoji]=useState(false);
 const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 const send=async()=>{if(!text.trim())return;await sendMessage({text:text.trim(),kind:'text',reply_to:reply?.id});setText('');setReply(null)};
 const file=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);await sendMessage({text:'',kind:f.type.startsWith('image/')?'image':'file',file_url:url,file_name:f.name,mime_type:f.type});e.target.value=''};
 return <section className="chat page">
  <div className="chat-status"><span>🔒</span> Messages are private-ready. <b>{partner?.online?'Your person is online':'Waiting for your person'}</b></div>
  <div className="messages">
   {messages.length===0&&<div className="empty"><MessageCircle size={35}/><h3>Start your little conversation</h3><p>Your first message will appear here.</p></div>}
   {messages.map(m=><MessageBubble key={m.id} m={m} mine={m.sender_id===localStorage.getItem('justus.uid')} onReply={()=>setReply(m)} onDelete={()=>toast('Delete can be wired to the database policy','info')}/>)}
   <div ref={end}/>
  </div>
  {reply&&<div className="reply-bar"><span>Replying to: {reply.text||reply.file_name}</span><button onClick={()=>setReply(null)}><X size={16}/></button></div>}
  {emoji&&<div className="emoji-tray">{['❤️','🥹','😘','🫶','✨','😂','😍','😌','💫','🤍'].map(e=><button key={e} onClick={()=>{setText(v=>v+e);setEmoji(false)}}>{e}</button>)}</div>}
  <div className="composer"><button className="icon-btn" onClick={()=>setEmoji(v=>!v)}><Smile/></button><label className="icon-btn"><Paperclip/><input hidden type="file" accept="image/*,.pdf,.doc,.docx,.zip" onChange={file}/></label><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Write something…"/><button className={`send ${text.trim()?'ready':''}`} onClick={send}><Send size={18}/></button></div>
 </section>
}
function MessageBubble({m,mine,onReply,onDelete}:{m:Message;mine:boolean;onReply:()=>void;onDelete:()=>void}){return <div className={`message-row ${mine?'mine':''}`} onContextMenu={e=>{e.preventDefault();onReply()}}><div className="bubble">{m.reply_to&&<div className="reply-preview">↳ replied message</div>}{m.kind==='image'&&m.file_url?<img className="chat-image" src={m.file_url} alt="shared"/>:m.kind==='file'?<div className="file-message"><FileIcon/><span>{m.file_name||'Attachment'}</span><Download size={16}/></div>:<span>{m.text}</span>}<small>{clock(new Date(m.created_at))} {mine&&(m.status==='read'?<CheckCheck size={13}/>:<Check size={13}/>)}</small><div className="bubble-actions"><button onClick={onReply}>Reply</button><button onClick={onDelete}><Trash2 size={12}/></button></div></div></div>}
function MomentsView({moments,userId,sendMoment,toast}:{moments:Moment[];userId:string;sendMoment:(c:string,f:File)=>Promise<void>;toast:any}){const [file,setFile]=useState<File|null>(null);const [caption,setCaption]=useState('');const [preview,setPreview]=useState('');const words=caption.trim()?caption.trim().split(/\s+/).length:0;const choose=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setFile(f);setPreview(URL.createObjectURL(f))};const send=async()=>{if(!file)return toast('Choose a photo first','error');if(words>20)return toast('Keep the message to 20 words','error');await sendMoment(caption.trim(),file);setFile(null);setPreview('');setCaption('')};return <section className="page"><div className="page-title"><div><span className="eyebrow">MOMENTS</span><h2>Little surprises</h2><p>One photo can become the other person’s little surprise.</p></div></div><div className="moment-composer"><label className="photo-picker">{preview?<img src={preview} alt="preview"/>:<><ImageIcon size={30}/><span>Choose photo</span></>}<input hidden type="file" accept="image/*" onChange={choose}/></label><input value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Write anything you want…"/><div className="moment-row"><span>{words}/20 words</span><button className="primary small-btn" onClick={send}>Done & share <Send size={15}/></button></div></div><div className="moments-grid">{moments.map(m=><article className="moment" key={m.id}><img src={m.image_url} alt="shared moment"/><div><span>{m.sender_id===userId?'You':'Your person'} · {ago(m.created_at)}</span><p>{m.caption||'♡'}</p></div></article>)}</div></section>}
function GamesView({toast}:{toast:any}){const [game,setGame]=useState<'hub'|'ludo'|'carrom'>('hub');if(game==='ludo')return <Ludo back={()=>setGame('hub')} toast={toast}/>;if(game==='carrom')return <Carrom back={()=>setGame('hub')} toast={toast}/>;return <section className="page"><div className="page-title"><div><span className="eyebrow">PLAY TOGETHER</span><h2>Two-player room</h2><p>Animated local play; connect game state to Realtime for remote turns.</p></div></div><div className="game-select"><button onClick={()=>setGame('ludo')}><span>🎲</span><h3>Ludo</h3><p>4 tokens each · six to enter · captures · safe cells · home</p><ChevronRight/></button><button onClick={()=>setGame('carrom')}><span>🪵</span><h3>Carrom</h3><p>Striker · coins · queen · pockets · scoring · turn system</p><ChevronRight/></button></div></section>}
const PATH=Array.from({length:52},(_,i)=>i);const SAFE=new Set([0,8,13,21,26,34,39,47]);
function Ludo({back,toast}:{back:()=>void;toast:any}){
 const [turn,setTurn]=useState(0),[dice,setDice]=useState(1),[rolling,setRolling]=useState(false),[tokens,setTokens]=useState<number[][]>([[-1,-1,-1,-1],[-1,-1,-1,-1]]),[winner,setWinner]=useState<number|null>(null);
 const roll=()=>{if(rolling||winner!==null)return;setRolling(true);let n=0;const t=setInterval(()=>{setDice(1+Math.floor(Math.random()*6));if(++n>=9){clearInterval(t);const d=1+Math.floor(Math.random()*6);setDice(d);setRolling(false);setTokens(ts=>{const next=ts.map(a=>[...a]);const active=next[turn];let idx=active.findIndex(x=>x>=0&&x<56);if(d===6){const base=active.findIndex(x=>x===-1);if(base>=0)idx=base}if(idx<0)idx=active.findIndex(x=>x>=0&&x<56);if(idx>=0){let pos=active[idx];if(pos===-1){if(d===6)pos=0}else{pos=Math.min(56,pos+d)}active[idx]=pos;if(pos>=0&&pos<52){const global=(pos+(turn?26:0))%52;if(!SAFE.has(global)){const other=1-turn;next[other]=next[other].map(o=>{const og=o<0?-99:(o+(other?26:0))%52;return og===global&&o<52?-1:o})}}}if(active.every(x=>x===56)){setWinner(turn);toast(`Player ${turn+1} reached home!`,'success');haptic('success')}if(d!==6)setTurn(x=>1-x);return next})}},75)};
 const reset=()=>{setTokens([[-1,-1,-1,-1],[-1,-1,-1,-1]]);setTurn(0);setWinner(null);setDice(1)};
 return <section className="game-screen"><div className="game-top"><button className="icon-btn" onClick={back}><ArrowLeft/></button><div><span>LUDO</span><b>{winner!==null?`Player ${winner+1} wins!`:`Player ${turn+1}'s turn`}</b></div><button className="icon-btn" onClick={reset}><RefreshCw/></button></div><div className="ludo-board"><div className="base red"><div className="base-title">PLAYER 2</div>{tokens[1].map((x,i)=><span key={i} className="home-token">{x===56?'✓':i+1}</span>)}</div><div className="track">{PATH.map(i=><span key={i} className={`${SAFE.has(i)?'safe ':''}${i===0?'start':''}`}>{SAFE.has(i)?'★':''}</span>)}</div><div className="base green"><div className="base-title">PLAYER 1</div>{tokens[0].map((x,i)=><span key={i} className="home-token">{x===56?'✓':i+1}</span>)}</div><div className="home-center">HOME<br/>♡</div>{tokens.flatMap((a,p)=>a.map((pos,i)=>pos>=0&&pos<52?(()=>{const g=(pos+(p?26:0))%52;const ang=(g/52)*Math.PI*2-Math.PI/2;return <span key={`${p}-${i}`} className={`moving-token p${p}`} style={{left:`calc(50% + ${Math.cos(ang)*36}% - 14px)`,top:`calc(50% + ${Math.sin(ang)*36}% - 14px)`}}>{p?'R':'G'}{i+1}</span>})():null))}</div><div className="ludo-controls"><button className={`dice ${rolling?'rolling':''}`} onClick={roll}>{dice}</button><p>{winner!==null?'Game over — restart to play again':dice===6?'Six! Token enters from base; roll again.':'Roll the dice for the active player.'}</p><div className="token-strip"><span>🟢 {tokens[0].filter(x=>x===56).length}/4 home</span><span>🔴 {tokens[1].filter(x=>x===56).length}/4 home</span></div></div><p className="game-note">★ safe cells cannot be captured. Landing on an opponent token captures it and sends it back to base.</p></section>
}
function Carrom({back,toast}:{back:()=>void;toast:any}){const ref=useRef<HTMLCanvasElement>(null);const [score,setScore]=useState([0,0]);const [turn,setTurn]=useState(0);const [aim,setAim]=useState({x:50,y:88});const [coins,setCoins]=useState(()=>Array.from({length:12},(_,i)=>({x:50+(i%6-2.5)*4,y:50+(Math.floor(i/6)-.5)*4,vx:0,vy:0,id:i,p:i===0?'queen':'coin'})));useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d')!;let raf=0;const d=()=>{const r=c.getBoundingClientRect();const sx=c.width/r.width,sy=c.height/r.height;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#d6b58a';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#6b4327';ctx.fillRect(22,22,c.width-44,c.height-44);ctx.strokeStyle='#f2e1bd';ctx.lineWidth=5;ctx.strokeRect(44,44,c.width-88,c.height-88);[[55,55],[c.width-55,55],[55,c.height-55],[c.width-55,c.height-55]].forEach(([x,y])=>{ctx.fillStyle='#17120f';ctx.beginPath();ctx.arc(x,y,17,0,7);ctx.fill()});coins.forEach(o=>{o.x+=o.vx;o.y+=o.vy;o.vx*=.985;o.vy*=.985;if(o.x<10||o.x>90)o.vx*=-.85;if(o.y<10||o.y>90)o.vy*=-.85;ctx.fillStyle=o.p==='queen'?'#b54b78':o.p==='coin'?(o.id%2?'#f4e7cf':'#242024'):'#fff';ctx.beginPath();ctx.arc(o.x/100*c.width,o.y/100*c.height,14,0,7);ctx.fill();ctx.strokeStyle='#ffffff55';ctx.stroke()});ctx.strokeStyle='#ffffff77';ctx.beginPath();ctx.moveTo(aim.x/100*c.width,aim.y/100*c.height);ctx.lineTo(50/100*c.width,82/100*c.height);ctx.stroke();raf=requestAnimationFrame(d)};d();return()=>cancelAnimationFrame(raf)},[coins,aim]);const shoot=()=>{const dx=50-aim.x,dy=82-aim.y;setCoins(v=>v.map((o,i)=>i===0?{...o,vx:dx*.09,vy:dy*.09}:o));haptic('medium');setTimeout(()=>{setScore(s=>{const n=[...s];n[turn]+=1;return n});setTurn(t=>1-t)},1200)};const pointer=(e:React.PointerEvent)=>{const r=ref.current!.getBoundingClientRect();setAim({x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100})};return <section className="game-screen"><div className="game-top"><button className="icon-btn" onClick={back}><ArrowLeft/></button><div><span>CARROM</span><b>Player {turn+1}'s turn</b></div><div className="score">{score[0]} — {score[1]}</div></div><div className="carrom"><canvas ref={ref} width={700} height={700} onPointerMove={pointer} onPointerUp={shoot}/></div><p className="game-note">Drag/aim around the striker and release. Coins rebound from the rails; pocketing scores and changes turn. Queen is the pink coin.</p><button className="secondary" onClick={()=>{setScore([0,0]);setTurn(0);toast('Carrom reset','success')}}>Restart game <RefreshCw size={16}/></button></section>}

type CallState={video:boolean;initiator:boolean};
function CallOverlay({call,profile,partner,channel,userId,pendingSignal,close,toast}:{call:CallState;profile:Profile;partner:any;channel:RealtimeChannel|null;userId:string;pendingSignal:any;close:()=>void;toast:any}){
 const localRef=useRef<HTMLVideoElement>(null),remoteRef=useRef<HTMLVideoElement>(null),pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null);
 const [connected,setConnected]=useState(false),[muted,setMuted]=useState(false),[camera,setCamera]=useState(call.video),[sharing,setSharing]=useState(false),[facing,setFacing]=useState<'user'|'environment'>('user');
 useEffect(()=>{let active=true;(async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:call.video});if(!active)return;stream.current=s;if(localRef.current)localRef.current.srcObject=s;const peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});pc.current=peer;s.getTracks().forEach(t=>peer.addTrack(t,s));peer.ontrack=e=>{if(remoteRef.current)remoteRef.current.srcObject=e.streams[0];setConnected(true)};peer.onicecandidate=e=>{if(e.candidate)channel?.send({type:'broadcast',event:'call-signal',payload:{from:userId,type:'ice',candidate:e.candidate}})};if(call.initiator){const offer=await peer.createOffer();await peer.setLocalDescription(offer);channel?.send({type:'broadcast',event:'call-signal',payload:{from:userId,type:'offer',video:call.video,offer}})}}catch{toast('Camera/microphone permission was denied','error')}})();return()=>{active=false;stream.current?.getTracks().forEach(t=>t.stop());pc.current?.close()}},[]);
 useEffect(()=>{const onSignal=async(e:any)=>{const p=e.detail;if(!pc.current||p.from===userId)return;if(p.type==='answer'){await pc.current.setRemoteDescription(p.answer);setConnected(true)}else if(p.type==='ice'){try{await pc.current.addIceCandidate(p.candidate)}catch{}}else if(p.type==='decline'){toast('Call declined','info');close()}};window.addEventListener('justus-call',onSignal);return()=>window.removeEventListener('justus-call',onSignal)},[channel,userId,toast,close]);
 useEffect(()=>{if(!pendingSignal||call.initiator||!pc.current)return;const accept=async()=>{const ok=window.confirm(`Incoming ${call.video?'video':'voice'} call from ${partner?.name||'your person'}. Accept?`);if(!ok){channel?.send({type:'broadcast',event:'call-signal',payload:{from:userId,type:'decline'}});close();return}await pc.current!.setRemoteDescription(pendingSignal.offer);const answer=await pc.current!.createAnswer();await pc.current!.setLocalDescription(answer);channel?.send({type:'broadcast',event:'call-signal',payload:{from:userId,type:'answer',answer}})};accept()},[pendingSignal,call.initiator,call.video,partner,channel,userId]);
 const toggleMute=()=>{stream.current?.getAudioTracks().forEach(t=>t.enabled=!t.enabled);setMuted(v=>!v);haptic('light')};
 const toggleCamera=()=>{stream.current?.getVideoTracks().forEach(t=>t.enabled=!t.enabled);setCamera(v=>!v)};
 const flip=async()=>{if(!call.video)return;const next=facing==='user'?'environment':'user';try{const s=await navigator.mediaDevices.getUserMedia({audio:true,video:{facingMode:next}});const track=s.getVideoTracks()[0];const sender=pc.current?.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(track);stream.current?.getVideoTracks().forEach(t=>t.stop());stream.current=s;if(localRef.current)localRef.current.srcObject=s;setFacing(next)}catch{toast('Camera switch is not available','error')}};
 const share=async()=>{try{const s=await (navigator.mediaDevices as any).getDisplayMedia({video:true});const track=s.getVideoTracks()[0];const sender=pc.current?.getSenders().find(x=>x.track?.kind==='video');if(sender)await sender.replaceTrack(track);track.onended=()=>setSharing(false);setSharing(true)}catch{toast('Screen sharing cancelled or unsupported','info')}};
 const decline=()=>{channel?.send({type:'broadcast',event:'call-signal',payload:{from:userId,type:'decline'}});close()};
 return <div className="call-modal"><div className="call-top"><div><span>{connected?'connected':'connecting…'}</span><h2>{call.video?'Video call':'Voice call'}</h2></div><span className="call-state"><i className={connected?'on':''}/>{connected?'live':'waiting'}</span></div><div className="video-stage"><video ref={remoteRef} autoPlay playsInline className="remote"/><div className={`remote-placeholder ${connected?'hide':''}`}><span className="call-big-icon">{call.video?'📹':'📞'}</span><b>{partner?.name||'Your person'}</b><span>{connected?'Connected':'Waiting for answer'}</span></div>{call.video&&<video ref={localRef} autoPlay muted playsInline className="local"/>}</div><div className="call-controls"><button onClick={toggleMute} className={muted?'danger':''}>{muted?<MicOff/>:<Mic/>}<span>{muted?'Unmute':'Mute'}</span></button>{call.video&&<button onClick={toggleCamera}><Video/><span>{camera?'Camera':'Camera off'}</span></button>}{call.video&&<button onClick={flip}><RefreshCw/><span>Flip</span></button>}{call.video&&<button onClick={share}><ScreenShare/><span>{sharing?'Sharing':'Share'}</span></button>}<button className="decline" onClick={decline}><Phone/><span>Decline</span></button></div><p className="call-note">Real WebRTC media. The two devices must share the same configured room channel. STUN is included; production deployments should add TURN for difficult networks.</p></div>
}
function Toasts({items}:{items:Toast[]}){return <div className="toasts" aria-live="polite">{items.map(t=><div className={`toast ${t.kind}`} key={t.id}><span>{t.kind==='success'?<Check/>:t.kind==='error'?<X/>:<Zap/>}</span>{t.text}</div>)}</div>}
function callSignal(payload:any){(window as any).__lastCallSignal=payload}
createRoot(document.getElementById('root')!).render(<App/>);
