-- JUST US: room-code connection + simple chat backend
-- Run this ONCE in Supabase SQL Editor.
-- This version deliberately uses plain tables + RPCs so the frontend can
-- work without the Supabase JS module and can fall back to HTTP polling.

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  created_at timestamptz not null default now(),
  created_by text,
  member_count integer not null default 0
);

create table if not exists public.room_members (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  device_id text not null,
  display_name text not null default 'You',
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(room_id,device_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  device_id text not null,
  display_name text not null default 'You',
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists messages_room_created_idx on public.messages(room_id,created_at);
create index if not exists members_room_idx on public.room_members(room_id);

alter table public.rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.messages enable row level security;

-- Public browser access is intentionally narrow:
-- room creation/join happens through the SECURITY DEFINER RPCs.
-- Messages can only be read/inserted for a room; the app still treats the
-- room code as the access gate. For stronger auth, add Supabase Auth later.

drop policy if exists "messages_read" on public.messages;
create policy "messages_read" on public.messages for select to anon,authenticated using (true);

drop policy if exists "messages_insert" on public.messages;
create policy "messages_insert" on public.messages for insert to anon,authenticated with check (char_length(body) between 1 and 1000);

create or replace function public.create_private_room(p_device_id text,p_display_name text)
returns table(id uuid,code text)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_code text;
  v_id uuid;
begin
  if p_device_id is null or length(trim(p_device_id)) < 4 then
    raise exception 'Invalid device';
  end if;

  -- Generate an unambiguous 6-character code.
  loop
    v_code := upper(substr(encode(gen_random_bytes(8),'hex'),1,6));
    begin
      insert into public.rooms(code,created_by) values(v_code,p_device_id) returning rooms.id into v_id;
      exit;
    exception when unique_violation then
      -- Try another code.
    end;
  end loop;

  insert into public.room_members(room_id,device_id,display_name)
  values(v_id,p_device_id,coalesce(nullif(trim(p_display_name),''),'You'));

  update public.rooms set member_count=1 where rooms.id=v_id;
  return query select v_id,v_code;
end;
$$;

create or replace function public.join_private_room(p_code text,p_device_id text,p_display_name text)
returns table(id uuid,code text)
language plpgsql
security definer
set search_path=public
as $$
declare v_room public.rooms%rowtype; v_count integer;
begin
  if p_device_id is null or length(trim(p_device_id)) < 4 then raise exception 'Invalid device'; end if;
  select * into v_room from public.rooms where rooms.code=upper(regexp_replace(trim(p_code),'\s','','g')) limit 1;
  if not found then raise exception 'Room not found. Check the exact code.'; end if;

  select count(*) into v_count from public.room_members where room_id=v_room.id;
  if v_count >= 2 and not exists(select 1 from public.room_members where room_id=v_room.id and device_id=p_device_id) then
    raise exception 'This room already has two people.';
  end if;

  insert into public.room_members(room_id,device_id,display_name,last_seen_at)
  values(v_room.id,p_device_id,coalesce(nullif(trim(p_display_name),''),'You'),now())
  on conflict(room_id,device_id) do update set display_name=excluded.display_name,last_seen_at=now();

  update public.rooms set member_count=(select count(*) from public.room_members where room_id=v_room.id) where rooms.id=v_room.id;
  return query select v_room.id,v_room.code;
end;
$$;

grant usage on schema public to anon,authenticated;
grant select,insert on public.messages to anon,authenticated;
grant execute on function public.create_private_room(text,text) to anon,authenticated;
grant execute on function public.join_private_room(text,text,text) to anon,authenticated;

-- IMPORTANT: if your existing project already has rooms/messages tables,
-- do NOT blindly run this file. Send the existing SQL/schema first so the
-- migration can be adapted instead of creating duplicate tables.
